feat: render markdown at server side
LevelUpWeb3/app pull request #83
Opened 2024-11-25 08:19 UTC by yqrashawn

## Summary
update pre-process scripts and rendering functions, so that makrdown pages `foo/[slug]/page.tsx` are rendered at `next build` time

## Detail
1. remove committed public/data/challenges/foo.json
1. update scripts/processFooMarkdown.js
    1. before ERC20.mdx -> public/data/xxx/ERC20.json
    after ERC20.mdx -> public/data/xxx/ERC20.mdx
    1. before fetch public/data/xxx/markdownData.json
    after fs readsync src/app/xxx/markdownData.json
    1. no more mdx-remote serialize, it will be done at `next build`

1. git ignore files generated by scripts/processXXXMarkdown.js
1. add `generateStaticParams` to `[slug]/page.tsx` so that MDX pages will be built at build time
1. remove the usage of `import { headers } from "next/headers"` in root layout
this makes all routes dynamic, although everything is known at build time

2024-12-02 02:30 UTC, Holybasil commented on src/app/challenges/[slug]/ChallengeViewer.tsx
> +    <MDXRemote
use `Suspense` to wrap the time-consuming server components rather than adding a loading page

2024-12-02 02:45 UTC, Holybasil requested changes

2024-12-02 02:45 UTC, Holybasil commented on src/constants/route.ts
>    ogImg: "/images/level-up-preview.png",
remove `ogImg` and `twitterImg` because `opengraph-image.ong` and `twitter-image.png`  are working now

2024-12-02 02:45 UTC, Holybasil commented on src/app/challenges/[slug]/ChallengeViewer.tsx
> +    <MDXRemote
use `Suspense` to wrap the time-consuming server components rather than adding a loading page, as well as other viewers

2024-12-03 01:34 UTC, yqrashawn commented
thanks for the review, @Holybasil 
ready for review again

2024-12-04 01:15 UTC, Holybasil approved these changes

2024-12-04 01:16 UTC, merged