Add profile page
LevelUpWeb3/app pull request #95
Opened 2024-12-23 12:25 UTC by zzq0826

2025-01-26 16:54 UTC, PrintRH reviewed
Mad respect for the huge lift! Left some comments @zzq0826

2025-01-27 01:15 UTC, Holybasil commented
![CleanShot 2025-01-27 at 09 13 56@2x](https://github.com/user-attachments/assets/577493a4-efaa-4fba-a3ab-036f765510a5)
```json
{
  "success": false,
  "error": "Vercel Blob: No token found. Either configure the `BLOB_READ_WRITE_TOKEN` environment variable, or pass a `token` option to your calls."
}
```

2025-01-27 02:13 UTC, Holybasil requested changes

2025-01-27 02:13 UTC, Holybasil commented on src/app/profile/components/ProfileModal.tsx
> +              onChange={(e) => setName(e.target.value)}
better to trim username here

2025-01-27 02:13 UTC, Holybasil commented on src/app/api/user/profile/route.ts
> +function validateUsername(username) {
better to have sensitive word detection

2025-01-27 02:13 UTC, Holybasil commented on src/app/profile/infoCard/index.tsx
for React Component, better to use `InfoCard` as the file name

2025-01-27 02:32 UTC, zzq0826 commented on src/app/events/eventsList.json
> +    "buttonDisabled": "true",
Reverted, sorry, I forgot to modify this!

2025-01-27 02:33 UTC, zzq0826 commented on src/app/solidity/[slug]/EditorPanel/Editor.tsx
>  import CongratualtionModal from "./CongratualtionModal";
Update.

2025-01-27 02:33 UTC, zzq0826 commented on .env.template
> +LEVEL_UP_BLOB_READ_WRITE_TOKEN=""
Fixed it, changed back to the default `BLOB_READ_WRITE_TOKEN`.

2025-01-27 02:38 UTC, zzq0826 commented on src/app/api/user/profile/route.ts
> +function validateUsername(username) {
Makes sense, will discuss this issue with the product. Currently, the name is only visible to the user, and we will optimize it in the future.

2025-01-27 02:43 UTC, zzq0826 commented on src/app/profile/components/ProfileModal.tsx
> +              onChange={(e) => setName(e.target.value)}
Great point, update.

2025-01-27 10:35 UTC, PrintRH approved these changes
LGTM!

2025-02-05 01:39 UTC, merged